todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

todo/webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'

urlpatterns = [
    path('', views.home, name="home"),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('notes/', views.notes, name='notes'),
    path('logout/', views.logout, name='logout'),
    path('edit/<int:note_id>', views.edit, name='edit'),
    path('delete/<int:note_id>', views.delete, name='delete'),
    path('complete/<int:note_id>', views.complete, name='complete')
]

todo/webapp/models.py
from django.db import models
from django.contrib.auth.models import User

class TodoItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    description = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.description+" - "+str(self.completed)

todo/webapp/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from django import forms

from django.forms.widgets import PasswordInput, TextInput

# register/create a user
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2'] # fields to display

#login a user
class LoginUserForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password'] # fields to display
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

todo/webapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CreateUserForm, LoginUserForm

from django.contrib.auth import authenticate
from django.contrib.auth.models import auth
from django.contrib.auth.decorators import login_required

from .models import TodoItem

#homepage
def home(request):
    return render(request, 'webapp/index.html')

#register a user
def register(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save() # save user to database
            return redirect('webapp:login')
    else:
        form = CreateUserForm()
    return render(request, 'webapp/register.html', {'form': form})

#login a user
def login(request):
    if request.method == 'POST':
        form = LoginUserForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            #check if user exists
            if user is not None:
                auth.login(request, user)
                return redirect('webapp:notes')
    else:
        form = LoginUserForm()
    context = {'form': form}
    return render(request, 'webapp/login.html', context=context)

#logout a user
def logout(request):
    auth.logout(request)
    return redirect('webapp:login')

#create a note/view notes
@login_required(login_url='webapp:login')
def notes(request):
    if request.method == 'POST':
        description = request.POST['description']
        if description.strip() != '':
            TodoItem.objects.create(user=request.user, description=description)
            
    my_notes = TodoItem.objects.order_by('completed','id').filter(user=request.user)
    context = {'todonotes': my_notes, 'user': request.user}
    return render(request, 'webapp/note.html', context=context)

#edit note
@login_required(login_url='webapp:login')
def edit(request, note_id):
    if request.method == 'POST':
        note = TodoItem.objects.get(pk=note_id)
        description = request.POST['description']
        if description.strip() != '':
            note.description = description
            note.save()
            return redirect('webapp:notes')
        else:
            return redirect('webapp:edit', note_id=note_id)
    
    note = get_object_or_404(TodoItem, pk=note_id)
    context = {'note': note}
    return render(request, 'webapp/edit.html', context=context)

#delete note
@login_required(login_url='webapp:login')
def delete(request, note_id):
    note = get_object_or_404(TodoItem, pk=note_id)
    note.delete()
    return redirect('webapp:notes')

#complete note
@login_required(login_url='webapp:login')
def complete(request, note_id):
    note = get_object_or_404(TodoItem, pk=note_id)
    if note.completed == True:
        note.completed = False
    else:
        note.completed = True
    note.save()
    return redirect('webapp:notes')

todo/webapp/templates/webapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Web App</title>
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/flatly/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <!-- create nav bar -->
    {% include 'webapp/navbar.html' %}

    <div class ="container">
        <br>

        {% block content %}
            <!-- place holder for other templates -->
        {% endblock %}

    </div>

    
    <script src="{% static 'js/app.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

todo/webapp/templates/webapp/edit.html
{% extends "webapp/base.html" %}

{% block content %}

    <head>
        
    </head>

    <body>
        <div class="container shadow-md p-5 form-layout" style="background-color: rgb(250, 217, 250);">

        <h1 style="text-align: center; font-family:'Brush Script MT', cursive; color: rgb(129, 56, 197);">My Notes</h1>

        <h3 style="text-align: center; font-family:'Brush Script MT', cursive; color: rgb(129, 56, 197);">Edit Note</h3>

        <hr style="border-color: white; border-width: 5px; width:100%">

        <form class="form-inline" method="POST" href="{% url 'webapp:edit' note.id %}">
            {% csrf_token %}
            <div class="form-group mx-sm-3 mb-2">
                <input class="form-control" type="text" name="description" autocomplete="off" value="{{note.description}}">
            </div>
        </form>
        
        </div>
    </body>
{% endblock %}

todo/webapp/templates/webapp/index.html
{% extends 'webapp/base.html' %}

{% block content %}
    <div class="text-center">

        <h2>ToDo List</h2>
        <h5>Organize your day!</h5>

        <hr>

        <a href="{% url 'webapp:register' %}" type="button" class="btn btn-primary">Get Started</a>
    
    </div>
{% endblock %}

todo/webapp/templates/webapp/login.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <body>
        <div class="container bg-light shadow-md p-5 form-layout">
            <h3> Login to your account </h3>
            <h5> start organizing!!! </h5>
            <hr>
            <br>

            <form method="post" autocomplete="off">
                {% csrf_token %}

                {{form|crispy}}

                <br>

                <button type="submit" class="btn btn-primary w-100 btn-block p-2"> Login </button>
            </form>

            <br>

            <div class="text-center">
                <a href="{% url 'webapp:register' %}"> Don't have an account? </a>
            </div>

            <br>
        </div>
    </body>
{% endblock %}

todo/webapp/templates/webapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark justify-content-center" style="background-color: rgb(112, 101, 101);">

        <a class="navbar-brand main-heading">            
            &nbsp; ToDoo App
        </a>
    
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse text-center" id="navbarNavDropdown">

                <ul class="navbar-nav mr-auto">
                    &nbsp;     &nbsp;     &nbsp; 
                        {% if user.is_authenticated %}
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'webapp:notes' %}">My Notes &nbsp; <i class="fa fa-home" aria-hidden="true"></i> </a>
                        </li>

                        &nbsp;     &nbsp;     &nbsp;

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'webapp:logout' %}">Sign out &nbsp; <i class="fa fa-sign-out" aria-hidden="true"></i> </a>
                        </li>
                </ul>
                        

                        {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webapp:register' %}"> Register </a>
                </li>

                &nbsp;     &nbsp;     &nbsp; 

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webapp:login' %}">Login</a>
                </li>

            {% endif %}
            
    </div>
    {% if user.is_authenticated %}
        <h2 style="text-align: right; color:aliceblue; font-family: 'Brush Script MT', cursive;">Welcome {{user.username}}</h2>
    {% endif %}
</nav>

todo/webapp/templates/webapp/note.html
{% extends "webapp/base.html" %}

{% block content %}

    <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>

    <body>
        <div class="container shadow-md p-5 form-layout" style="background-color: rgb(250, 217, 250); ">

        <h1 style="text-align: center; font-family:'Brush Script MT', cursive; color: rgb(129, 56, 197);">My Notes</h1>

        <form class="form-inline" method="post">
            {% csrf_token %}
            <div class="form-group mx-sm-3 mb-2">
                <input class="form-control" placeholder="Add item" type="text" name="description" autocomplete="off">
            </div>
        </form>

        <hr style="border-color: white; border-width: 5px; width:100%">

        {% for note in todonotes %}
            <div>
                <div class="icon" style="display:inline; ">
                    <form class="form-inline" style="display:inline;" method="POST" action="{% url 'webapp:complete' note.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn1">
                            {% if note.completed %}
                                <i class="material-icons md-green md-24">check_circle</i>
                            {% else %}
                                <i class="material-icons md-light md-24">circle</i>    
                            {% endif %}
                        </button>
                    </form>
                </div>

                <div class="text" style="display:inline; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
                    
                    {% if note.completed %}
                        <a href="{% url 'webapp:edit' note.id %}" class="my-link" style="text-decoration: none;"><strike>{{note.description}}</strike></a>
                    {% else %}
                        <a href="{% url 'webapp:edit' note.id %}" class="my-link" style="text-decoration: none;"> {{note.description}} </a>
                    {% endif %}

                </div>

                <div class="icon" style="display:inline; ">
                    <form class="form-inline" style="display:inline;" method="POST" action="{% url 'webapp:delete' note.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn2">
                            <i class="material-icons md-red md-24">close</i>
                        </button>
                    </form>
                </div>
                

                <br>
                <br>
            </div>
        {% endfor %}
        </div>
    </body>
{% endblock %}

todo/webapp/templates/webapp/register.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <body>
        <div class="container bg-light shadow-md p-5 form-layout">
            <h3> Create you account </h3>
            <h5> start organizing!!! </h5>
            <hr>
            <br>

            <form method="post" autocomplete="off">
                {% csrf_token %}

                {{form|crispy}}

                <br>

                <button type="submit" class="btn btn-primary w-100 btn-block p-2"> Create Account </button>
            </form>

            <br>

            <div class="text-center">
                <a href="{% url 'webapp:login' %}"> Already have an account? </a>
            </div>

            <br>
        </div>
    </body>
{% endblock %}